version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: todo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo123
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "8082:80"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

